# Generated by Django 5.2.3 on 2025-12-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
